baseurl = "https://jmachadofreitas.github.io/"
title = "jmachadofreitas"
theme = "hugo-coder"
locale = "en"
defaultcontentlanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 20

# Enable Disqus comments
# disqusShortname = "jmachadofreitas"

[markup.highlight]
style = "github-dark"


[languages.en]
languageName = "🇬🇧"
locale = "en"
weight = 1


[languages.de]
languageName = "🇩🇪"
locale = "de-DE"
weight = 2

[params]
  author = "João Machado de Freitas"
  info = ["Data Scientist", "Analytics & Machine Learning"]
  description = "João's personal website"
  keywords = "personal,developer,portfolio" # ,blog
  avatarurl = "images/avatar.jpeg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  # Right To Left, shift content direction for languagues such as Hebrew
  rtl = false

  dateFormat = "January 2, 2006"
  since = 2023

  enableTwemoji = true

  colorScheme = "auto"  # auto, light, dark
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]
  # customRemoteJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
 name = "LinkedIn"
 icon = "fa fa-2x fa-linkedin"
 weight = 1
 url = "https://www.linkedin.com/in/jmachadofreitas/"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/jmachadofreitas/"
[[params.social]]
 name = "Google Scholar"
 icon = "fa-brands fa-google-scholar fa-2x"
 weight = 3
 url = "https://scholar.google.com/citations?user=QcXsxLAAAAAJ&hl=en"
# [[params.social]]
#  name = "ORCID"
#  icon = "fa-brands fa-orcid fa-2x"
#  weight = 3
#  url = "https://orcid.org/0000-0001-8867-7574"


# Menu links
[[languages.en.menu.main]]
 name = "About"
 weight = 1
 url = "about/"
[[languages.de.menu.main]]
 name = "Über mich"
 weight = 1
 url = "about/"
#[[menu.main]]
#  name = "Blog"
#  weight = 1
#  url  = "posts/"
